// backend/utils/validators.js
const CREDIT_CATEGORIES_FOUNDATION = ['MEMBERSHIP_FEE', 'MONTHLY_FEE', 'DONATION', 'INTEREST', 'OTHER_INCOME'];
const DEBIT_CATEGORIES_FOUNDATION = ['EXPENSE'];

const CREDIT_CATEGORIES_VILLAGE = ['POND_AUCTION', 'GOVERNMENT_FUND', 'DONATION', 'FESTIVAL_COLLECTION', 'INTEREST', 'OTHER_INCOME'];
const DEBIT_CATEGORIES_VILLAGE = ['INFRASTRUCTURE_EXPENSE', 'FESTIVAL_EXPENSE', 'MAINTENANCE_EXPENSE', 'SALARY_EXPENSE', 'UTILITY_EXPENSE', 'OTHER_EXPENSE'];

const PAYMENT_MODES = ['CASH', 'UPI', 'BANK_TRANSFER', 'CHEQUE'];

const validatePhone = (phone) => /^[6-9]\d{9}$/.test(phone);

module.exports = {
  CREDIT_CATEGORIES_FOUNDATION,
  DEBIT_CATEGORIES_FOUNDATION,
  CREDIT_CATEGORIES_VILLAGE,
  DEBIT_CATEGORIES_VILLAGE,
  PAYMENT_MODES,
  validatePhone
};